import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ar' }]
}

export default function RootLayout({ children ,  params  }) {
  
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Header lang={params.lang}/>
        {children}
      </body>
    </html>
  );
}
